### ISSUE TITLE
Provide implementation for Microprofile JSON parser

### ISSUE THREAD

**Issue by hendrikebbers** [OpenElements/hiero-enterprise-java#127]
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to this project or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'good first issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3AOpenElements+archived%3Afalse+label%3A%22good+first+issue%22) is to help you make your first contribution.

## 👾 Description of the issue
The class `com.openelements.hiero.microprofile.implementation.MirrorNodeJsonConverterImpl` needs to be implemented using the `jakarta.json.*` API. The implementation for Spring that is based on Jackson, is a good reference to see how the JSON needs to be parsed. It can be found at `com.openelements.hiero.spring.implementation.MirrorNodeJsonConverterImpl`. The `Optional<AccountInfo> toAccountInfo(@NonNull JsonObject node)` method is already implemented to give an idea how the implementation should look like. Next to that unit tests (by passing hand-made json to the methods) must be added.

## Suggested solution
Create a new test class or extend the existing test suite for `AccountClientImpl` to include tests for the `getAccountBalance` method. Follow the established testing pattern using JUnit to validate both positive and negative scenarios for this method.

## 📋 Step by step guide to do a contribution
If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. 
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** to your branch. Here it is important to sign-off you commits to fullfill the [Developer Certificate of Origin (DCO)](https://developercertificate.org). More information can be found [in our contribution guideline](https://github.com/OpenElements/.github/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-dco).
- [ ] **Start a Pull Request (PR)**: in the hedera-enterprise repository
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the community for support.
- [ ] **Wait for reviews:** Members of the community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of our community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional informantion

If you have any questions, just ask us directly in this issue by adding a comment. A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by Ndacyayisenga-droid** [comment]
It's nnow assigned to you @theboywholived

**Comment by theboywholived** [comment]
I have created a pull request for my changes(UTs are pending)
https://github.com/OpenElements/hiero-enterprise-java/pull/132

Before that, local tests are failing on my system, even without my changes on running `./mvnw verify`

```[ERROR] Errors: 
[ERROR]   ProtocolLayerClientAccountTests.init:27 » IllegalArgument failed to construct sequence from byte[]: unknown tag 1 encountered
[ERROR]   ProtocolLayerClientTokenTests.init:25 » IllegalArgument failed to construct sequence from byte[]: unknown tag 1 encountered
```

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.031 s <<< FAILURE! -- in com.openelements.hiero.base.test.ProtocolLayerClientAccountTests
[ERROR] com.openelements.hiero.base.test.ProtocolLayerClientAccountTests -- Time elapsed: 0.031 s <<< ERROR!
java.lang.IllegalArgumentException: failed to construct sequence from byte[]: unknown tag 1 encountered
        at org.bouncycastle.provider@1.76/org.bouncycastle.asn1.ASN1Sequence.getInstance(Unknown Source)
        at org.bouncycastle.provider@1.76/org.bouncycastle.asn1.sec.ECPrivateKey.getInstance(Unknown Source)
        at sdk@2.32.0/com.hedera.hashgraph.sdk.PrivateKey.fromBytesDER(PrivateKey.java:231)
        at sdk@2.32.0/com.hedera.hashgraph.sdk.PrivateKey.fromBytes(PrivateKey.java:198)
        at sdk@2.32.0/com.hedera.hashgraph.sdk.PrivateKey.fromString(PrivateKey.java:151)
        at com.openelements.hiero.base.test/com.openelements.hiero.base.test.HieroTestContext.<init>(HieroTestContext.java:29)
        at com.openelements.hiero.base.test/com.openelements.hiero.base.test.ProtocolLayerClientAccountTests.init(ProtocolLayerClientAccountTests.java:27)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)


```

**Comment by Ndacyayisenga-droid** [comment]
@theboywholived To execute the test classes, you must either run them independently or create a dedicated pull request to test within the CI pipeline.

Refer to the [instructions](https://github.com/OpenElements/hiero-enterprise-java?tab=readme-ov-file#built-the-project) for building the project. Note that your testnet account lacks sufficient HBARs to execute all repository tests. Alternatively, you can verify the build while skipping tests using: `./mvnw verify -DskipTests`

**Comment by Ndacyayisenga-droid** [comment]
The github environment has enough HBARs to run all the tests
